name: Download Kube-Prometheus-Stack Helm Chart

on:
  workflow_dispatch:
    inputs:
      helm_version:
        description: 'Kube-Prometheus-Stack Helm Chart Version'
        required: true
        default: '88.5.2'
        type: string

jobs:
  download-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Pull Helm Chart
        run: |
          # 添加仓库并更新
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          
          # 创建输出目录
          mkdir -p offline-chart
          
          # 下载指定版本的 Helm Chart (.tgz)
          helm pull prometheus-community/kube-prometheus-stack --version ${{ inputs.helm_version }} --destination offline-chart/
          
          # 解压 Chart
          tar -zxvf offline-chart/kube-prometheus-stack-${{ inputs.helm_version }}.tgz -C offline-chart/
          
          # 修正路径：新版 crds 直接在根目录的 crds/ 下
          cp -r offline-chart/kube-prometheus-stack/crds ./offline-crds

      - name: Archive CRDs and Chart
        run: |
          # 把解压后的整个 chart 目录打包成 zip
          cd offline-chart
          zip -r ../kube-prometheus-stack-${{ inputs.helm_version }}-source.zip kube-prometheus-stack/
          cd ..
          
          # 把 crds 打包
          zip -r offline-crds.zip offline-crds/

      - name: Upload Chart & CRDs Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kube-prometheus-stack-chart-and-crds-${{ inputs.helm_version }}
          path: |
            offline-chart/*.tgz
            offline-chart/kube-prometheus-stack-*-source.zip
            offline-crds.zip
